#!/usr/bin/env bash
# install and configure HAproxy on your lb-01 server.
sudo apt -y install haproxy
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOT
frontend http_web
    bind *:80
    default_backend rgw
backend rgw
    balance roundrobin
    server 4300-web-01  54.175.184.137:80 check
    server 4300-web-02  34.228.80.2:80 check
EOT
sudo service haproxy restart
